### ISSUE TITLE
README

### ISSUE THREAD

**Issue by whippingdot** [Repl-it-Coders/repl-it-weekly#1]
Please add a README.md so I know what this is. Also, try not to create random repos, please. Like what is this for. It might be useful, but this is our org. You are not supposed to create repos which have no meaning to our org. Please transfer this to your account.

**Comment by anonymt-dev** [comment]
Yea, do add a readme so other ppl know what this is for.

**Comment by iop3** [comment]
LMFAO @Tr1angular literally deleted the readme d30a6df @whippingdot @theiocoder

**Comment by anonymt-dev** [comment]
Yea, I know lel, make a new one! XD

**Comment by iop3** [comment]
dont ask me lol, i didn't make this repo. Ask @zplusfour @firefish111

**Comment by anonymt-dev** [comment]
> dont ask me lol

I wasn't asking you I was just generally saying someone who can should make a new readme lol

**Comment by iop3** [comment]
lol ok

**Comment by iop3** [comment]
also congrats on the `is-a.dev` domain :)

**Comment by anonymt-dev** [comment]
thx :)

**Comment by iop3** [comment]
np

**Comment by whippingdot** [comment]
who are you @theiocoder

**Comment by anonymt-dev** [comment]
wdym @whippingdot

**Comment by anonymt-dev** [comment]
> wdym @whippingdot

besides the fact i used to be _CodingRedpanda_

**Comment by whippingdot** [comment]
Oh ok. I was asking that...
